### ISSUE TITLE
add github action check for helm-docs

### ISSUE THREAD

**Issue by TomHellier** [parca-dev/helm-charts#15]
The github pr CI should detect whether the readme has been templatesd according to the readme.md.tpl file, and fail the build if not matching

**Comment by rlex** [comment]
good idea, grafana charts repo have an example https://github.com/grafana/helm-charts/blob/main/.github/workflows/linter.yml

**Comment by rlex** [comment]
implemented in https://github.com/parca-dev/helm-charts/pull/16
