### ISSUE TITLE
agent: Socket path should be left empty by default

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/helm-charts#4]
The charts specify `socketPath` flag by default and the value is for `containerd` runtime  (`/run/containerd/containerd.sock`). Unfortunately, this prevents us from inferring the correct container runtime for the agent. This should be left blank by default.

https://github.com/parca-dev/helm-charts/blob/b2756c0f6612f4e6fd5a1c0f8cf317add765f4c7/charts/parca/templates/agent-daemonset.yaml#L44

https://github.com/parca-dev/helm-charts/blob/6798d97c6a5fc7be84a6089d13542d7a27d2e3cc/charts/parca/values.yaml#L19

**Comment by rlex** [comment]
should be fixed in 2.0.0
