### ISSUE TITLE
Add the ability to use a Parca Server deployed in a different cluster

### ISSUE THREAD

**Issue by Pryz** [parca-dev/helm-charts#7]
Thanks for this chart. 

Currently the chart is assuming that the agents and server will be deployed in the same Kubernetes cluster. In some setup, we might see servers deploy in a separate cluster, in a centralized fashion.

Are you open to support this use case ?

**Comment by rlex** [comment]
I think it should be pretty easy - just make https://github.com/parca-dev/helm-charts/blob/master/charts/parca/templates/agent-daemonset.yaml#L40 configurable. I'll try to do that this week.

**Comment by rlex** [comment]
In 2.0.1 you can use agent.storeAddress to manually override parca server address https://github.com/parca-dev/helm-charts/commit/81a8846a06567385d5dc3ab6a924e4e8b9c5f4c4

**Comment by Pryz** [comment]
Should we also disable all the server resources (deployment and friends) when we set the server address ?

**Comment by rlex** [comment]
oh, my bad, i was pretty sure server can be disabled too. I'll fix that in coming days.

**Comment by rlex** [comment]
Should be possible now with server.enabled: false

**Comment by Pryz** [comment]
Thanks much !
